.PHONY: clean All

All:
	@echo "----------Building project:[ Deep_Copy - Debug ]----------"
	@cd "Deep_Copy" && "$(MAKE)" -f  "Deep_Copy.mk"
clean:
	@echo "----------Cleaning project:[ Deep_Copy - Debug ]----------"
	@cd "Deep_Copy" && "$(MAKE)" -f  "Deep_Copy.mk" clean
