.PHONY: clean All

All:
	@echo "----------Building project:[ Section_13_Revision_Challenge - Debug ]----------"
	@cd "Section_13_Revision_Challenge" && "$(MAKE)" -f  "Section_13_Revision_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section_13_Revision_Challenge - Debug ]----------"
	@cd "Section_13_Revision_Challenge" && "$(MAKE)" -f  "Section_13_Revision_Challenge.mk" clean
