.PHONY: clean All

All:
	@echo "----------Building project:[ Section_13_New_Challenge - Debug ]----------"
	@cd "Section_13_New_Challenge" && "$(MAKE)" -f  "Section_13_New_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section_13_New_Challenge - Debug ]----------"
	@cd "Section_13_New_Challenge" && "$(MAKE)" -f  "Section_13_New_Challenge.mk" clean
