.PHONY: clean All

All:
	@echo "----------Building project:[ section_12_challenge - Debug ]----------"
	@cd "section_12_challenge" && "$(MAKE)" -f  "section_12_challenge.mk"
clean:
	@echo "----------Cleaning project:[ section_12_challenge - Debug ]----------"
	@cd "section_12_challenge" && "$(MAKE)" -f  "section_12_challenge.mk" clean
