.PHONY: clean All

All:
	@echo "----------Building project:[ feedback - Debug ]----------"
	@cd "feedback" && "$(MAKE)" -f  "feedback.mk"
clean:
	@echo "----------Cleaning project:[ feedback - Debug ]----------"
	@cd "feedback" && "$(MAKE)" -f  "feedback.mk" clean
