.PHONY: clean All

All:
	@echo "----------Building project:[ Overloading_Copy_Assignment - Debug ]----------"
	@cd "Overloading_Copy_Assignment" && "$(MAKE)" -f  "Overloading_Copy_Assignment.mk"
clean:
	@echo "----------Cleaning project:[ Overloading_Copy_Assignment - Debug ]----------"
	@cd "Overloading_Copy_Assignment" && "$(MAKE)" -f  "Overloading_Copy_Assignment.mk" clean
