.PHONY: clean All

All:
	@echo "----------Building project:[ redefining_Base_Class_Methods - Debug ]----------"
	@cd "redefining_Base_Class_Methods" && "$(MAKE)" -f  "redefining_Base_Class_Methods.mk"
clean:
	@echo "----------Cleaning project:[ redefining_Base_Class_Methods - Debug ]----------"
	@cd "redefining_Base_Class_Methods" && "$(MAKE)" -f  "redefining_Base_Class_Methods.mk" clean
