.PHONY: clean All

All:
	@echo "----------Building project:[ nexpe - Debug ]----------"
	@cd "nexpe" && "$(MAKE)" -f  "nexpe.mk"
clean:
	@echo "----------Cleaning project:[ nexpe - Debug ]----------"
	@cd "nexpe" && "$(MAKE)" -f  "nexpe.mk" clean
