.PHONY: clean All

All:
	@echo "----------Building project:[ Overloading_Operator_Challenge_1 - Debug ]----------"
	@cd "Overloading_Operator_Challenge_1" && "$(MAKE)" -f  "Overloading_Operator_Challenge_1.mk"
clean:
	@echo "----------Cleaning project:[ Overloading_Operator_Challenge_1 - Debug ]----------"
	@cd "Overloading_Operator_Challenge_1" && "$(MAKE)" -f  "Overloading_Operator_Challenge_1.mk" clean
