.PHONY: clean All

All:
	@echo "----------Building project:[ Deriving_our_first_class - Debug ]----------"
	@cd "Deriving_our_first_class" && "$(MAKE)" -f  "Deriving_our_first_class.mk"
clean:
	@echo "----------Cleaning project:[ Deriving_our_first_class - Debug ]----------"
	@cd "Deriving_our_first_class" && "$(MAKE)" -f  "Deriving_our_first_class.mk" clean
